version: '3.3'

services:
  web:
    build: .
    command: gunicorn django_vsps.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
   
  watchtower: #hlída změny v lokalní složce z repo
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300 # Check every 5 minutes
    restart: unless-stopped